<?php

$aboutSectionModel = [
    "model" => [
        "preview" => [],
        "name" => "aboutsection",
        "label" => "About Section",
        "info" => "",
        "type" => "singleton",
        "fields" => [
            [
                "name" => "title",
                "type" => "text",
                "label" => "Title",
                "info" => "",
                "group" => "",
                "i18n" => false,
                "required" => true,
                "multiple" => false,
                "meta" => [],
                "opts" => [
                    "multiline" => false,
                    "showCount" => true,
                    "readonly" => false,
                    "placeholder" => null,
                    "minlength" => null,
                    "maxlength" => null,
                    "list" => null,
                ],
            ],
            [
                "name" => "content",
                "type" => "wysiwyg",
                "label" => "Content",
                "info" => "",
                "group" => "",
                "i18n" => false,
                "required" => false,
                "multiple" => false,
                "meta" => [],
                "opts" => [],
            ],
            [
                "name" => "images",
                "type" => "asset",
                "label" => "Images",
                "info" => "",
                "group" => "",
                "i18n" => false,
                "required" => false,
                "multiple" => true,
                "meta" => [],
                "opts" => [],
            ],
            [
                "name" => "show_view_more",
                "type" => "boolean",
                "label" => "Show View More Button",
                "info" => "",
                "group" => "",
                "i18n" => false,
                "required" => true,
                "multiple" => false,
                "meta" => [],
                "opts" => [],
            ],
            [
                "name" => "view_more_button_text",
                "type" => "text",
                "label" => "View More Button Text",
                "info" => "",
                "group" => "",
                "i18n" => false,
                "required" => false,
                "multiple" => false,
                "meta" => [],
                "opts" => [
                    "multiline" => false,
                    "showCount" => true,
                    "readonly" => false,
                    "placeholder" => null,
                    "minlength" => null,
                    "maxlength" => null,
                    "list" => null,
                ],
            ],
            [
                "name" => "view_more_button_link",
                "type" => "text",
                "label" => "View More Button Link",
                "info" => "",
                "group" => "",
                "i18n" => false,
                "required" => false,
                "multiple" => false,
                "meta" => [],
                "opts" => [
                    "multiline" => false,
                    "showCount" => true,
                    "readonly" => false,
                    "placeholder" => null,
                    "minlength" => null,
                    "maxlength" => null,
                    "list" => null,
                ],
            ],
        ],
        "group" => "Section",
        "meta" => null,
        "_created" => 1729492771,
        "_modified" => 1729499579,
        "color" => null,
        "revisions" => false,
    ],
    "isUpdate" => false,
];
