<?php

$blogsModel = [
    "model" => [
        "preview" => [],
        "name" => "blogs",
        "label" => "Blogs",
        "info" => "",
        "type" => "collection",
        "fields" => [
            [
                "name" => "title",
                "type" => "text",
                "label" => "Title",
                "info" => "",
                "group" => "",
                "i18n" => false,
                "required" => true,
                "multiple" => false,
                "meta" => [],
                "opts" => [
                    "multiline" => false,
                    "showCount" => true,
                    "readonly" => false,
                    "placeholder" => null,
                    "minlength" => null,
                    "maxlength" => null,
                    "list" => null,
                ],
            ],
            [
                "name" => "slug",
                "type" => "text",
                "label" => "Slug",
                "info" => "Slug version of the Title for friendly URL. Try it at https://slugify.online/",
                "group" => "",
                "i18n" => false,
                "required" => true,
                "multiple" => false,
                "meta" => [],
                "opts" => [
                    "multiline" => false,
                    "showCount" => true,
                    "readonly" => false,
                    "placeholder" => null,
                    "minlength" => null,
                    "maxlength" => null,
                    "list" => null,
                ],
            ],
            [
                "name" => "content",
                "type" => "wysiwyg",
                "label" => "Content",
                "info" => "",
                "group" => "",
                "i18n" => false,
                "required" => true,
                "multiple" => false,
                "meta" => [],
                "opts" => [],
            ],
            [
                "name" => "category",
                "type" => "contentItemLink",
                "label" => "Category",
                "info" => "",
                "group" => "",
                "i18n" => false,
                "required" => true,
                "multiple" => false,
                "meta" => [],
                "opts" => [
                    "link" => "blogcategories",
                    "filter" => null,
                ],
            ],
            [
                "name" => "excerpt",
                "type" => "text",
                "label" => "Excerpt",
                "info" => "",
                "group" => "",
                "i18n" => false,
                "required" => true,
                "multiple" => false,
                "meta" => [],
                "opts" => [
                    "multiline" => true,
                    "showCount" => true,
                    "readonly" => false,
                    "placeholder" => null,
                    "minlength" => null,
                    "maxlength" => null,
                    "list" => null,
                ],
            ],
            [
                "name" => "thumbnail",
                "type" => "asset",
                "label" => "Thumbnail",
                "info" => "",
                "group" => "",
                "i18n" => false,
                "required" => true,
                "multiple" => false,
                "meta" => [],
                "opts" => [],
            ],
            [
                "name" => "published_at",
                "type" => "datetime",
                "label" => "Published At",
                "info" => "",
                "group" => "",
                "i18n" => false,
                "required" => true,
                "multiple" => false,
                "meta" => [],
                "opts" => [],
            ],
            [
                "name" => "keywords",
                "type" => "text",
                "label" => "Keywords",
                "info" => "",
                "group" => "SEO",
                "i18n" => false,
                "required" => false,
                "multiple" => false,
                "meta" => [],
                "opts" => [
                    "multiline" => false,
                    "showCount" => true,
                    "readonly" => false,
                    "placeholder" => null,
                    "minlength" => null,
                    "maxlength" => null,
                    "list" => null,
                ],
            ],
        ],
        "group" => "",
        "meta" => null,
        "_created" => time(),
        "_modified" => time(),
        "color" => null,
        "revisions" => false,
    ],
    "isUpdate" => false,
];
