<?php

$blogCategoriesModel = [
    "model" => [
        "preview" => [],
        "name" => "blogcategories",
        "label" => "Blog Categories",
        "info" => "",
        "type" => "collection",
        "fields" => [
            [
                "name" => "title",
                "type" => "text",
                "label" => "Title",
                "info" => "",
                "group" => "",
                "i18n" => false,
                "required" => true,
                "multiple" => false,
                "meta" => [],
                "opts" => [
                    "multiline" => false,
                    "showCount" => true,
                    "readonly" => false,
                    "placeholder" => null,
                    "minlength" => null,
                    "maxlength" => null,
                    "list" => null,
                ],
            ],
            [
                "name" => "slug",
                "type" => "text",
                "label" => "Slug",
                "info" => "Slug version of the Title for friendly URL. Try it at https://slugify.online/",
                "group" => "",
                "i18n" => false,
                "required" => true,
                "multiple" => false,
                "meta" => [],
                "opts" => [
                    "multiline" => false,
                    "showCount" => true,
                    "readonly" => false,
                    "placeholder" => null,
                    "minlength" => null,
                    "maxlength" => null,
                    "list" => null,
                ],
            ],
        ],
        "group" => "",
        "meta" => null,
        "_created" => time(),
        "_modified" => time(),
        "color" => null,
        "revisions" => false,
    ],
    "isUpdate" => false,
];
