<?php

$callToActionModel = [
    "model" => [
        "preview" => [],
        "name" => "calltoaction",
        "label" => "Call To Action",
        "info" => "",
        "type" => "singleton",
        "fields" => [
            [
                "name" => "content",
                "type" => "text",
                "label" => "Content",
                "info" => "",
                "group" => "",
                "i18n" => false,
                "required" => true,
                "multiple" => false,
                "meta" => [],
                "opts" => [
                    "multiline" => false,
                    "showCount" => true,
                    "readonly" => false,
                    "placeholder" => null,
                    "minlength" => null,
                    "maxlength" => null,
                    "list" => null,
                ],
            ],
            [
                "name" => "button_text",
                "type" => "text",
                "label" => "Button Text",
                "info" => "",
                "group" => "",
                "i18n" => false,
                "required" => true,
                "multiple" => false,
                "meta" => [],
                "opts" => [
                    "multiline" => false,
                    "showCount" => true,
                    "readonly" => false,
                    "placeholder" => null,
                    "minlength" => null,
                    "maxlength" => null,
                    "list" => null,
                ],
            ],
            [
                "name" => "button_link",
                "type" => "text",
                "label" => "Button Link",
                "info" => "",
                "group" => "",
                "i18n" => false,
                "required" => true,
                "multiple" => false,
                "meta" => [],
                "opts" => [
                    "multiline" => false,
                    "showCount" => true,
                    "readonly" => false,
                    "placeholder" => null,
                    "minlength" => null,
                    "maxlength" => null,
                    "list" => null,
                ],
            ],
        ],
        "group" => "Section",
        "meta" => null,
        "_created" => time(),
        "_modified" => time(),
        "color" => null,
        "revisions" => false,
    ],
    "isUpdate" => false,
];
