<?php

$footerModel = [
    "model" => [
        "preview" => [],
        "name" => "footer",
        "label" => "Footer",
        "info" => "",
        "type" => "singleton",
        "fields" => [
            [
                "name" => "footer_left",
                "type" => "set",
                "label" => "Footer Left",
                "info" => "First column in Footer",
                "group" => "",
                "i18n" => false,
                "required" => true,
                "multiple" => false,
                "meta" => [],
                "opts" => [
                    "fields" => [
                        [
                            "name" => "title",
                            "type" => "text",
                            "label" => "Title",
                            "info" => "",
                            "group" => "",
                            "i18n" => false,
                            "required" => true,
                            "multiple" => false,
                            "meta" => [],
                            "opts" => [
                                "multiline" => false,
                                "showCount" => true,
                                "readonly" => false,
                                "placeholder" => null,
                                "minlength" => null,
                                "maxlength" => null,
                                "list" => null,
                            ],
                        ],
                        [
                            "name" => "content",
                            "type" => "wysiwyg",
                            "label" => "Content",
                            "info" => "",
                            "group" => "",
                            "i18n" => false,
                            "required" => true,
                            "multiple" => false,
                            "meta" => [],
                            "opts" => [],
                        ],
                    ],
                    "display" => null,
                ],
            ],
            [
                "name" => "footer_center",
                "type" => "set",
                "label" => "Footer Center",
                "info" => "Second column in Footer",
                "group" => "",
                "i18n" => false,
                "required" => true,
                "multiple" => false,
                "meta" => [],
                "opts" => [
                    "fields" => [
                        [
                            "name" => "title",
                            "type" => "text",
                            "label" => "Title",
                            "info" => "",
                            "group" => "",
                            "i18n" => false,
                            "required" => true,
                            "multiple" => false,
                            "meta" => [],
                            "opts" => [
                                "multiline" => false,
                                "showCount" => true,
                                "readonly" => false,
                                "placeholder" => null,
                                "minlength" => null,
                                "maxlength" => null,
                                "list" => null,
                            ],
                        ],
                        [
                            "name" => "content",
                            "type" => "wysiwyg",
                            "label" => "Content",
                            "info" => "",
                            "group" => "",
                            "i18n" => false,
                            "required" => true,
                            "multiple" => false,
                            "meta" => [],
                            "opts" => [],
                        ],
                    ],
                    "display" => null,
                ],
            ],
            [
                "name" => "footer_middle",
                "type" => "set",
                "label" => "Footer Middle",
                "info" => "Third column in Footer",
                "group" => "",
                "i18n" => false,
                "required" => false,
                "multiple" => false,
                "meta" => [],
                "opts" => [
                    "fields" => [
                        [
                            "name" => "title",
                            "type" => "text",
                            "label" => "Title",
                            "info" => "",
                            "group" => "",
                            "i18n" => false,
                            "required" => true,
                            "multiple" => false,
                            "meta" => [],
                            "opts" => [
                                "multiline" => false,
                                "showCount" => true,
                                "readonly" => false,
                                "placeholder" => null,
                                "minlength" => null,
                                "maxlength" => null,
                                "list" => null,
                            ],
                        ],
                        [
                            "name" => "content",
                            "type" => "wysiwyg",
                            "label" => "Content",
                            "info" => "",
                            "group" => "",
                            "i18n" => false,
                            "required" => true,
                            "multiple" => false,
                            "meta" => [],
                            "opts" => [],
                        ],
                    ],
                    "display" => null,
                ],
            ],
            [
                "name" => "footer_right",
                "type" => "set",
                "label" => "Footer Right",
                "info" => "Fourth column in Footer",
                "group" => "",
                "i18n" => false,
                "required" => false,
                "multiple" => false,
                "meta" => [],
                "opts" => [
                    "fields" => [
                        [
                            "name" => "title",
                            "type" => "text",
                            "label" => "Title",
                            "info" => "",
                            "group" => "",
                            "i18n" => false,
                            "required" => true,
                            "multiple" => false,
                            "meta" => [],
                            "opts" => [
                                "multiline" => false,
                                "showCount" => true,
                                "readonly" => false,
                                "placeholder" => null,
                                "minlength" => null,
                                "maxlength" => null,
                                "list" => null,
                            ],
                        ],
                        [
                            "name" => "content",
                            "type" => "wysiwyg",
                            "label" => "Content",
                            "info" => "",
                            "group" => "",
                            "i18n" => false,
                            "required" => true,
                            "multiple" => false,
                            "meta" => [],
                            "opts" => [],
                        ],
                    ],
                    "display" => null,
                ],
            ],
        ],
        "group" => "Section",
        "meta" => null,
        "_created" => time(),
        "_modified" => time(),
        "color" => null,
        "revisions" => false,
    ],
    "isUpdate" => false,
];
