<?php

$mainNavigationModel = [
    "model" => [
        "preview" => [],
        "name" => "mainnavigation",
        "label" => "Main Navigation",
        "info" => "",
        "type" => "collection",
        "fields" => [
            [
                "name" => "title",
                "type" => "text",
                "label" => "Title",
                "info" => "",
                "group" => "",
                "i18n" => false,
                "required" => true,
                "multiple" => false,
                "meta" => [],
                "opts" => [
                    "multiline" => false,
                    "showCount" => true,
                    "readonly" => false,
                    "placeholder" => null,
                    "minlength" => null,
                    "maxlength" => null,
                    "list" => null,
                ],
            ],
            [
                "name" => "link",
                "type" => "text",
                "label" => "Link",
                "info" => "",
                "group" => "",
                "i18n" => false,
                "required" => true,
                "multiple" => false,
                "meta" => [],
                "opts" => [
                    "multiline" => false,
                    "showCount" => true,
                    "readonly" => false,
                    "placeholder" => null,
                    "minlength" => null,
                    "maxlength" => null,
                    "list" => null,
                ],
            ],
            [
                "name" => "banner",
                "type" => "asset",
                "label" => "Banner",
                "info" => "",
                "group" => "",
                "i18n" => false,
                "required" => false,
                "multiple" => false,
                "meta" => [],
                "opts" => [],
            ],
            [
                "name" => "ordering",
                "type" => "number",
                "label" => "Ordering",
                "info" => "",
                "group" => "",
                "i18n" => false,
                "required" => true,
                "multiple" => false,
                "meta" => [],
                "opts" => [],
            ],
        ],
        "group" => "Section",
        "meta" => null,
        "_created" => time(),
        "_modified" => time(),
        "color" => null,
        "revisions" => false,
    ],
    "isUpdate" => false,
];
