<?php

$websiteInformationModel = [
    "model" => [
        "preview" => [],
        "name" => "websiteinformation",
        "label" => "Website Information",
        "info" => "",
        "type" => "singleton",
        "fields" => [
            [
                "name" => "sitename",
                "type" => "text",
                "label" => "Sitename",
                "info" => "",
                "group" => "",
                "i18n" => false,
                "required" => true,
                "multiple" => false,
                "meta" => [],
                "opts" => [
                    "multiline" => false,
                    "showCount" => true,
                    "readonly" => false,
                    "placeholder" => null,
                    "minlength" => null,
                    "maxlength" => null,
                    "list" => null,
                ],
            ],
            [
                "name" => "description",
                "type" => "text",
                "label" => "Description",
                "info" => "",
                "group" => "",
                "i18n" => false,
                "required" => false,
                "multiple" => false,
                "meta" => [],
                "opts" => [
                    "multiline" => true,
                    "showCount" => true,
                    "readonly" => false,
                    "placeholder" => null,
                    "minlength" => null,
                    "maxlength" => null,
                    "list" => null,
                ],
            ],
            [
                "name" => "keywords",
                "type" => "text",
                "label" => "Keywords",
                "info" => "",
                "group" => "",
                "i18n" => false,
                "required" => false,
                "multiple" => false,
                "meta" => [],
                "opts" => [
                    "multiline" => true,
                    "showCount" => true,
                    "readonly" => false,
                    "placeholder" => null,
                    "minlength" => null,
                    "maxlength" => null,
                    "list" => null,
                ],
            ],
            [
                "name" => "author",
                "type" => "text",
                "label" => "Author",
                "info" => "",
                "group" => "",
                "i18n" => false,
                "required" => false,
                "multiple" => false,
                "meta" => [],
                "opts" => [
                    "multiline" => false,
                    "showCount" => true,
                    "readonly" => false,
                    "placeholder" => null,
                    "minlength" => null,
                    "maxlength" => null,
                    "list" => null,
                ],
            ],
            [
                "name" => "address",
                "type" => "text",
                "label" => "Address",
                "info" => "",
                "group" => "",
                "i18n" => false,
                "required" => true,
                "multiple" => false,
                "meta" => [],
                "opts" => [
                    "multiline" => true,
                    "showCount" => true,
                    "readonly" => false,
                    "placeholder" => null,
                    "minlength" => null,
                    "maxlength" => null,
                    "list" => null,
                ],
            ],
            [
                "name" => "email",
                "type" => "text",
                "label" => "Email",
                "info" => "",
                "group" => "",
                "i18n" => false,
                "required" => true,
                "multiple" => false,
                "meta" => [],
                "opts" => [
                    "multiline" => false,
                    "showCount" => true,
                    "readonly" => false,
                    "placeholder" => null,
                    "minlength" => null,
                    "maxlength" => null,
                    "list" => null,
                ],
            ],
            [
                "name" => "phone",
                "type" => "text",
                "label" => "Phone",
                "info" => "",
                "group" => "",
                "i18n" => false,
                "required" => false,
                "multiple" => false,
                "meta" => [],
                "opts" => [
                    "multiline" => false,
                    "showCount" => true,
                    "readonly" => false,
                    "placeholder" => null,
                    "minlength" => null,
                    "maxlength" => null,
                    "list" => null,
                ],
            ],
            [
                "name" => "google_map_url",
                "type" => "text",
                "label" => "Google Map URL",
                "info" => "",
                "group" => "",
                "i18n" => false,
                "required" => false,
                "multiple" => false,
                "meta" => [],
                "opts" => [
                    "multiline" => false,
                    "showCount" => true,
                    "readonly" => false,
                    "placeholder" => null,
                    "minlength" => null,
                    "maxlength" => null,
                    "list" => null,
                ],
            ],
            [
                "name" => "logo",
                "type" => "asset",
                "label" => "Logo",
                "info" => "",
                "group" => "",
                "i18n" => false,
                "required" => false,
                "multiple" => false,
                "meta" => [],
                "opts" => [],
            ],
            [
                "name" => "favicon",
                "type" => "asset",
                "label" => "Favicon",
                "info" => "",
                "group" => "",
                "i18n" => false,
                "required" => false,
                "multiple" => false,
                "meta" => [],
                "opts" => [],
            ],
        ],
        "group" => "Settings",
        "meta" => null,
        "_created" => time(),
        "_modified" => time(),
        "color" => null,
        "revisions" => false,
    ],
    "isUpdate" => false,
];
